version: "3.8"

services:
  phpservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: phpapp:latest
    container_name: php-crud-app
    restart: always
    expose:
      - "80"
    volumes:
      - ./src:/var/www/html
    env_file:
      - .env  

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf   # ✅ mount only the file
      - ./nginx/ssl:/etc/nginx/ssl                            # ✅ SSL certs
      - ./src:/var/www/html                                   # optional (static files)
    depends_on:
      - phpservice
    restart: unless-stopped
    
  #dbservice:
    #container_name: dbcontainer
    #image: mysql:8.0
    #restart: always
    #environment:
      #MYSQL_ROOT_PASSWORD: rootpass
      #MYSQL_DATABASE: test_db
      #MYSQL_USER: testuser
      #MYSQL_PASSWORD: testpass
    #volumes:
      #- ./db_data:/var/lib/mysql
      #- ./db_init:/docker-entrypoint-initdb.d
    #ports:
      #- "3306:3306"

  #phpmyadminservice:
    #container_name: phpmyadmincontainer
    #image: phpmyadmin/phpmyadmin
    #restart: always
    #ports:
      #- "8081:80"
    #environment:
      #PMA_HOST: dbservice
      #MYSQL_ROOT_PASSWORD: rootpass
    #depends_on:
      #- dbservice
